### ISSUE TITLE
why closed code?

### ISSUE THREAD

**Issue by Juanito9001** [ErmanSayin/Themely#138]
@ErmanSayin i really love this aplication, it`s my favorite, but i only have a question... why do you close the code??? privacy or someone was stealing it? why? because a lot of people say that and i want to know the truth about this decision
BTW... sorry if my english it`s no good and my question is dumb

**Comment by pillows2** [comment]
So, a few weeks ago this all went down; someone made the first 3DS malware. When someone said that on the Discord, erman said "that it's a good idea" and then Themely went closed source. Since no one can trust erman (especially that he bought a Switch themes website and added pornography to it (he's underage BTW)) a developer made a superior app called Anemone. Just use that instead.

**Comment by ErmanSayin** [comment]
closed source was my initial choice I had anyway, and since the "community" went toxic on me for stuff like leaving a forum

**Comment by Juanito9001** [comment]
@ErmanSayin Thank you for your answer, and thanks for aclarate the theme of the false malware on themely, i always knew it, and always trust in this app
