### ISSUE TITLE
License change invalid

### ISSUE THREAD

**Issue by astronautlevel2** [ErmanSayin/Themely#84]
GPLv3 requires all contributors to approve a relicense of the software. During the time the program was GPLv3, you accepted #1 and #2 from @Robz8, making him a contributor to Themely. Therefore, you need his explicit permission to change Themely's license to All Rights Reserved. 

(Pointed out by SciresM, I had forgotten about that clause)

**Comment by astronautlevel2** [comment]
In addition, there are multiple commits such as https://github.com/ErmanSayin/Themely/commit/97595a38d11f0075618023a9bdcd917af09d997b which implement other's work. These people are also contributors under GPL. This means that at the very least, This means that all of these people:

@ZetaDesigns for German translation
@theheroGAC for Italian translation
@Jubash for Portuguese translation
@Ann0ying for Russian translation
@umbjolt for Spanish translation

Are required to give their consent to the change in license to All Rights Reserved..

**Comment by Ann0ying** [comment]
I'm agreeing.

**Comment by daedreth** [comment]
For those visiting here wondering what to do next, here is a short guide: https://www.gnu.org/licenses/gpl-violation.html

**Comment by astronautlevel2** [comment]
More contributors mentioned in commits:
@Brawl345
@Omegadrien
@MarcuzD

There is 1 additional conntributors who made changes but was not credited. They are still defined as contributors under the GPLv3.

@Uyuiyu with PR https://github.com/ErmanSayin/Themely/pull/68/files, closed and the manually merged in https://github.com/ErmanSayin/Themely/commit/0e6a14be735abb78167759a86586b46229944c7e

**Comment by theheroGAC** [comment]
I'm agreeing.

**Comment by ErmanSayin** [comment]
reverted

**Comment by astronautlevel2** [comment]
This is no longer relevant as the license change was reverted.

**Comment by ahoischen** [comment]
This is relevant again as the license has been changed to ARR again.
@ErmanSayin All people noted above have contributed code to this project. They own the copyright on their code. **All** copyright holders need to formally agree to a license change, not just the original creator of the project. Because you have made changes to the source and have now released this modified version in binary form, you are obligated to provide all who request it access to your source code under the conditions of the GNU GPLv3.

I hereby request access to the source code of the latest release of Themely. You may choose to publicly release the source or send it to me in private.

**Comment by ErmanSayin** [comment]
All contributions have been removed from the closed source version.
