### ISSUE TITLE
MIT Licenced, but you've removed the source code?

### ISSUE THREAD

**Issue by ojbr** [ErmanSayin/Themely#90]
https://github.com/ErmanSayin/Themely/commit/501f112f0bfe78ad7cc64cdb5e308375f5230ce7

Change removes the source code? Why? That's the whole point of GitHub... To share source code. C'mon now. You're closing off source access for an MIT Licenced application? There's no sense in that. If you want a means to distribute your app, use the GitHub releases feature.

**Comment by ahoischen** [comment]
While I do agree that removing the source goes against Github's purpose, I just wanted to note that the app was GPLv3. He was allowed to change it to MIT for the files that are in the latest commit since he was the only contributor.

**Comment by ErmanSayin** [comment]
It's not MIT, it's ARR.

**Comment by ojbr** [comment]
I think you've misunderstood the licensing behind GPLv3. 
With GPLv3, you *must* open source any changes that you make to later versions.

**Comment by ErmanSayin** [comment]
@ojbr That doesn't apply to the copyright holder (me). The README says some of the licenses used uses the MIT license, and it specifies that the actual app is ARR.

**Comment by ahoischen** [comment]
No, the actual app is not ARR. You have built the binaries using GPLv3 licensed code by multiple contributors. The current code-base in 501f112 can be licensed to your liking since it doesn't include other people's work, but all previous commits and all work based on them remain GPLv3 licensed.

Also: If you ever decide to release a new version you must [license it under the GPLv3](https://www.gnu.org/licenses/gpl-faq.en.html#TheGPLSaysModifiedVersions) and [make the source available to the public](https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic).

**Comment by ErmanSayin** [comment]
@ahoischen As I said, that doesn't apply to me, as the copyright holder.

Any future issues/PRs opened about this topic will be closed & locked with or without response.
